### ISSUE TITLE
Update documenation for “Build from factory”

### ISSUE THREAD

**Issue by mkempe** [chaijs/chai-factories#1]
Hi there,

The documentation says:

```
Build from factory

var user = chai.factory('person');
console.log(user);
```

But i have to use and looked into the source:

```
var user = chai.create('person');
console.log(user);
```

Is this correct? If so, i would update the documenation and README and send you a request.

PS: Thanks for Chai.js, its awesome.

**Comment by vesln** [comment]
Yeah, the docs are wrong. I'd love to merge a pull request that fixes this. Thank you!
